#!/usr/bin/env python3
"""
Export YouTube cookies from Chrome to Netscape cookies.txt format.
Requires: Chrome closed, Python 3.x
"""

import sqlite3
import os
import sys
from pathlib import Path

# Chrome cookie database locations
CHROME_COOKIES = {
    'darwin': Path.home() / 'Library/Application Support/Google/Chrome/Default/Cookies',
    'linux': Path.home() / '.config/google-chrome/Default/Cookies',
}

def get_chrome_cookies_path():
    """Get Chrome cookies database path for current OS."""
    platform = sys.platform
    if platform == 'darwin':
        return CHROME_COOKIES['darwin']
    elif platform.startswith('linux'):
        return CHROME_COOKIES['linux']
    else:
        raise Exception(f"Unsupported platform: {platform}")

def export_youtube_cookies(output_file='cookies.txt'):
    """Export YouTube cookies to Netscape format."""
    cookies_db = get_chrome_cookies_path()

    if not cookies_db.exists():
        print(f"❌ Chrome cookies not found at: {cookies_db}")
        print("Make sure Chrome is installed and you've visited YouTube.")
        return False

    # Copy database to temp location (Chrome might have it locked)
    import shutil
    import tempfile
    temp_db = Path(tempfile.gettempdir()) / 'cookies_temp.db'

    try:
        shutil.copy2(cookies_db, temp_db)
    except Exception as e:
        print(f"❌ Failed to copy cookies database: {e}")
        print("Make sure Chrome is CLOSED before running this script.")
        return False

    try:
        # Connect to copied database
        conn = sqlite3.connect(temp_db)
        cursor = conn.cursor()

        # Query YouTube cookies
        cursor.execute("""
            SELECT host_key, name, value, path, expires_utc, is_secure, is_httponly
            FROM cookies
            WHERE host_key LIKE '%youtube.com%' OR host_key LIKE '%google.com%'
            ORDER BY host_key, name
        """)

        cookies = cursor.fetchall()
        conn.close()

        if not cookies:
            print("❌ No YouTube cookies found. Please login to YouTube in Chrome first.")
            return False

        # Write in Netscape format
        with open(output_file, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file was generated by export-cookies.py\n")
            f.write("# Edit at your own risk.\n\n")

            for cookie in cookies:
                host, name, value, path, expires, secure, httponly = cookie

                # Convert Chrome's expires_utc (microseconds since 1601) to Unix timestamp
                if expires > 0:
                    # Chrome uses Windows epoch (1601-01-01), Unix uses 1970-01-01
                    unix_timestamp = int((expires / 1000000) - 11644473600)
                else:
                    unix_timestamp = 0

                # Netscape format: domain, flag, path, secure, expiration, name, value
                domain_flag = "TRUE" if host.startswith('.') else "FALSE"
                secure_flag = "TRUE" if secure else "FALSE"

                line = f"{host}\t{domain_flag}\t{path}\t{secure_flag}\t{unix_timestamp}\t{name}\t{value}\n"
                f.write(line)

        print(f"✅ Exported {len(cookies)} cookies to {output_file}")
        print(f"\nNext steps:")
        print(f"1. Copy cookies.txt to Raspberry Pi: scp {output_file} ${{RPI_USER}}@${{RPI_IP}}:~/yt-daily-player/")
        print(f"2. Restart container: ssh ${{RPI_USER}}@${{RPI_IP}} 'cd ~/yt-daily-player && docker compose restart'")
        return True

    except Exception as e:
        print(f"❌ Error reading cookies: {e}")
        return False
    finally:
        # Cleanup temp database
        if temp_db.exists():
            temp_db.unlink()

if __name__ == '__main__':
    print("YouTube Cookie Exporter")
    print("=" * 50)
    print("\n⚠️  Make sure Chrome is CLOSED before running this!\n")

    output = 'cookies.txt'
    if len(sys.argv) > 1:
        output = sys.argv[1]

    success = export_youtube_cookies(output)
    sys.exit(0 if success else 1)
